version: '3.8'

x-web-image: &web-image
  build:
    context: .
    dockerfile: Dockerfile
    target: web

x-worker-image: &worker-image
  build:
    context: .
    dockerfile: Dockerfile
    target: worker

x-app-volumes: &app-volumes
  volumes:
    - './storage:/var/www/html/storage'

x-app-environment: &app-environment
  AUTORUN_ENABLED: '${AUTORUN_ENABLED}'
  APP_NAME: '${APP_NAME}'
  APP_ENV: '${APP_ENV}'
  APP_KEY: '${APP_KEY}'
  APP_PREVIOUS_KEYS: '${APP_PREVIOUS_KEYS}'
  APP_DEBUG: '${APP_DEBUG}'
  APP_TIMEZONE: '${APP_TIMEZONE}'
  APP_URL: '${APP_URL}'
  APP_LOCALE: '${APP_LOCALE}'
  APP_FALLBACK_LOCALE: '${APP_FALLBACK_LOCALE}'
  APP_FAKER_LOCALE: '${APP_FAKER_LOCALE}'
  APP_MAINTENANCE_DRIVER: '${APP_MAINTENANCE_DRIVER}'
  APP_MAINTENANCE_STORE: '${APP_MAINTENANCE_STORE}'
  BCRYPT_ROUNDS: '${BCRYPT_ROUNDS}'
  LOG_CHANNEL: '${LOG_CHANNEL}'
  LOG_STACK: '${LOG_STACK}'
  LOG_DEPRECATIONS_CHANNEL: '${LOG_DEPRECATIONS_CHANNEL}'
  LOG_LEVEL: '${LOG_LEVEL}'
  DB_CONNECTION: '${DB_CONNECTION}'
  DB_HOST: '${DB_HOST}'
  DB_PORT: '${DB_PORT}'
  DB_DATABASE: '${DB_DATABASE}'
  DB_USERNAME: '${DB_USERNAME}'
  DB_PASSWORD: '${DB_PASSWORD}'
  SESSION_DRIVER: '${SESSION_DRIVER}'
  SESSION_LIFETIME: '${SESSION_LIFETIME}'
  SESSION_ENCRYPT: '${SESSION_ENCRYPT}'
  SESSION_PATH: '${SESSION_PATH}'
  SESSION_DOMAIN: '${SESSION_DOMAIN}'
  BROADCAST_CONNECTION: '${BROADCAST_CONNECTION}'
  FILESYSTEM_DISK: '${FILESYSTEM_DISK}'
  QUEUE_CONNECTION: '${QUEUE_CONNECTION}'
  CACHE_STORE: '${CACHE_STORE}'
  CACHE_PREFIX: '${CACHE_PREFIX}'
  MEMCACHED_HOST: '${MEMCACHED_HOST}'
  REDIS_CLIENT: '${REDIS_CLIENT}'
  REDIS_HOST: '${REDIS_HOST}'
  REDIS_PASSWORD: '${REDIS_PASSWORD}'
  REDIS_PORT: '${REDIS_PORT}'
  MAIL_MAILER: '${MAIL_MAILER}'
  MAIL_HOST: '${MAIL_HOST}'
  MAIL_PORT: '${MAIL_PORT}'
  MAIL_USERNAME: '${MAIL_USERNAME}'
  MAIL_PASSWORD: '${MAIL_PASSWORD}'
  MAIL_ENCRYPTION: '${MAIL_ENCRYPTION}'
  MAIL_FROM_ADDRESS: '${MAIL_FROM_ADDRESS}'
  MAIL_FROM_NAME: '${MAIL_FROM_NAME}'
  AWS_ACCESS_KEY_ID: '${AWS_ACCESS_KEY_ID}'
  AWS_SECRET_ACCESS_KEY: '${AWS_SECRET_ACCESS_KEY}'
  AWS_DEFAULT_REGION: '${AWS_DEFAULT_REGION}'
  AWS_BUCKET: '${AWS_BUCKET}'
  AWS_USE_PATH_STYLE_ENDPOINT: '${AWS_USE_PATH_STYLE_ENDPOINT}'
  VITE_APP_NAME: '${APP_NAME}'
  SENTRY_LARAVEL_DSN: '${SENTRY_LARAVEL_DSN}'
  OPENAI_API_KEY: '${OPENAI_API_KEY}'
  OPENAI_ORGANIZATION: '${OPENAI_ORGANIZATION}'

services:
  app:
    <<: [*web-image, *app-volumes]
    environment:
      <<: *app-environment
      PHP_FPM_POOL_NAME: "app"

  worker:
    <<: [*worker-image, *app-volumes]
    command: [ "php", "/var/www/html/artisan", "queue:work", "--tries=3" ]
    environment:
      <<: *app-environment
      PHP_FPM_POOL_NAME: "app_queue_worker"
    deploy:
      replicas: ${QUEUE_WORKERS:-1}
    healthcheck:
      test: [ "CMD", "healthcheck-queue" ]
      start_period: 10s
    stop_signal: SIGTERM

  scheduler:
    <<: [*worker-image, *app-volumes]
    command: [ "php", "/var/www/html/artisan", "schedule:work" ]
    environment:
      <<: *app-environment
      PHP_FPM_POOL_NAME: "app_scheduler"
    stop_signal: SIGTERM
    healthcheck:
      test: [ "CMD", "healthcheck-schedule" ]
      start_period: 10s